language: python

python: "2.7"

install:
 - pip install pytest pytest-cov
 - pip install git+https://github.com/ladybug-tools/ladybug.git@master
 # - pip install runmanager

script:
  - py.test --cov=. tests/

after_success:
  - coverage report
  - coveralls
